### PR TITLE
Optimize Code

### PR DESCRIPTION
**Pull request by ThePyProgrammer**
Hi. I'm assuming your name is Param. I was actually looking through your code and found many long-winded code pieces that could have been shortened, with usage of some unnecessary classes and a loaded requirements.txt for a file that honestly only used BeautifulSoup4. I also realised after shortening down the code that the project didn't actually require many files, hence I added a file `all.py` that contains all my new code. I hope you will look into this. Thank you.

### CODE REVIEW

**Comment by Param3103** [comment]
Hey PyProgrammer, thanks for your review. Now that I see it, your version is much neater and understandable.

**Comment by ThePyProgrammer** [comment]
Do you want me to move this to another branch instead? So that your original version is sustained. I can always just close this request and create another.

**Comment by Param3103** [comment]
That will be great :)

**Comment by ThePyProgrammer** [comment]
Ok then, I shall do that.

**Comment by ThePyProgrammer** [comment]
oh I never actually did this 💀 , maybe I'll do it some day.

**Comment by Param3103** [comment]
Hahahaha...i think a better option will be to collab on something lol

**Comment by ThePyProgrammer** [comment]
So true, post A Levels 👀

**Pull request closed without merging**
